name: TEALScript CI
on:
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run algokit localnet
      run: pipx install algokit && algokit localnet start

    - name: Install bun
      run: npm i -g bun

    - name: Install modules
      run: bun install --frozen-lockfile

    - name: Ensure version constant is up-to-date
      run: bun scripts/version.ts

    - name: Run ESLint
      run: bun lint

    - name: Run tests
      run: bun test

    - name: Run examples
      run: bun run-examples

    - name: Compile all
      run: bun compile-all

    - name: Web test
      run: bun web-test

