name: TEALScript CI
on:
  pull_request:
    branches: [ release, dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run sandbox
      run: git clone https://github.com/algorand/sandbox && ./sandbox/sandbox up -v dev

    - name: Install modules
      run: yarn

    - name: Run ESLint
      run: yarn run lint

    - name: Run tests
      run: yarn test

    - name: Run example artifact tests
      run: yarn run test-example-artifacts

    - name: Install ARC12 test dependencies
      run: pip3 install -r ./examples/arc12/tests/requirements.txt

    - name: Run ARC12 tests
      run: python3 -m pytest ./examples/arc12/tests

