name: TEALScript CI
on:
  pull_request:
    branches: [ main, dev ]
jobs:
  windows-smoketest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tsx and dependencies
      run: npm i -g tsx && npm i

    - name: Compile all
      env: 
        SKIP_ALGOD: 'true'
      run: tsx src/bin/tealscript.ts ./**/*.algo.ts ./
